theme = "TechBlog"
languageCode = "en-us"
baseurl = "https://tech-globe.netlify.app/"
title = "TechGlobe"

author = "Max Muster"
copyright = "Copyright © 2022, Max Muster, all rights reserved."


enableRobotsTXT = true

[params]
    name = "TechGlobe"
    subtitle = "Stay up-to-date with tech"
    description = "A world renowend blog covering the worlds latest news in Tech with Journalists all around the Globe."
    favicon = "favicon.ico"

    instagram = "https://www.instagram.com/"
    youtube = "https://www.youtube.com/"
    twitter = "https://twitter.com/home"
    facebook = "https://facebook.com/"
    tiktok = "https://www.tiktok.com/"

[build]
  writeStats = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'
